"""
Stage 7 — report: render the teardown as Markdown (for humans) and JSON (for machines).

The Markdown leads with the licence/adoption posture on purpose — how you may use what
follows is the first thing a reader needs to know.
"""
import json

from . import util


def to_json(result):
    """A clean, serialisable view (drops the in-memory-only graph internals)."""
    slim = dict(result)
    gmap = dict(slim.get("map", {}))
    gmap.pop("_file_text", None)
    gmap.pop("_file_defs", None)
    # keep only the top files/symbols in the machine view — the map can be huge
    gmap["files"] = gmap.get("files", [])[:40]
    gmap["symbols"] = [{k: v for k, v in s.items() if k != "excerpt"} for s in gmap.get("symbols", [])[:40]]
    slim["map"] = gmap
    return json.dumps(slim, indent=2, default=str)


def to_markdown(result):
    fp = result["fingerprint"]
    td = result["teardown"]
    ad = result["adoption"]
    pos = result["posture"]
    jewels = result["jewels"]
    gmap = result["map"]

    L = []
    L.append("# oni teardown — %s" % result["target"])
    if result.get("ref"):
        L.append("_ref: `%s`_" % result["ref"])
    L.append("")
    # --- posture banner first ---
    L.append("> **Adoption posture — %s**  \n> %s" % (pos["spdx"], pos["banner"]))
    L.append(">  \n> %s" % pos["rule"])
    L.append("")

    # --- snapshot ---
    L.append("## Snapshot")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Primary language | %s |" % (fp.get("primary_language") or "—"))
    L.append("| Size | %d files · %s LOC · %s |" % (
        fp["total_files"], f"{fp['total_loc']:,}", util.human_bytes(fp["total_bytes"])))
    L.append("| Licence | %s (%s) |" % (fp["license"]["spdx"], fp["license"]["name"]))
    sig = fp["signals"]
    L.append("| Signals | %s |" % ", ".join(
        [k for k, v in sig.items() if v] or ["—"]))
    if td.get("_model"):
        L.append("| Teardown model | %s |" % td["_model"])
    L.append("")
    top_langs = list(fp["languages"].items())[:6]
    if top_langs:
        L.append("**Languages:** " + " · ".join("%s %d" % (k, v["loc"]) for k, v in top_langs))
        L.append("")

    # --- what / how ---
    L.append("## What it is")
    L.append("")
    L.append(td.get("what", "—"))
    L.append("")
    L.append("## How it works")
    L.append("")
    L.append(td.get("how_it_works", "—"))
    L.append("")

    # --- architecture ---
    L.append("## Architecture")
    L.append("")
    L.append("Top-level areas by centrality (where the important code concentrates):")
    L.append("")
    for c in gmap["clusters"][:10]:
        L.append("- **%s/** — %d files" % (c["dir"], c["files"]))
    if result.get("entrypoints"):
        L.append("")
        L.append("**Entrypoints:** " + ", ".join("`%s`" % e for e in result["entrypoints"]))
    L.append("")

    # --- crown jewels ---
    L.append("## Crown jewels")
    L.append("")
    L.append("The highest-centrality symbols — study these first; the mechanism lives here.")
    L.append("")
    for j in jewels:
        L.append("### `%s` — %s" % (j["name"], j["kind"]))
        L.append("`%s:%d` · %d referrers · centrality %.4f" % (j["file"], j["line"], j["referrers"], j["score"]))
        if j["excerpt"]:
            lang = util.lang_of(j["file"]) or ""
            L.append("")
            L.append("```" + (lang.lower() if lang else ""))
            L.append(j["excerpt"])
            L.append("```")
        L.append("")

    # --- patterns / strengths / weaknesses ---
    if td.get("patterns"):
        L.append("## Notable patterns")
        L.append("")
        for p in td["patterns"]:
            L.append("- %s" % p)
        L.append("")
    if td.get("strengths") or td.get("weaknesses"):
        L.append("## Strengths & weaknesses")
        L.append("")
        for s in td.get("strengths", []):
            L.append("- ✅ %s" % s)
        for w in td.get("weaknesses", []):
            L.append("- ⚠️ %s" % w)
        L.append("")

    # --- adoption plan ---
    L.append("## Adoption plan (clean-room)")
    L.append("")
    if ad.get("summary"):
        L.append("_%s_" % ad["summary"])
        L.append("")
    if ad.get("adopt"):
        L.append("| Pattern | Build natively | Effort | Why |")
        L.append("|---|---|---|---|")
        for a in ad["adopt"]:
            L.append("| %s | %s | %s | %s |" % (
                a.get("pattern", "").replace("|", "\\|"),
                a.get("build", "").replace("|", "\\|"),
                a.get("effort", "?"),
                a.get("why", "").replace("|", "\\|")))
        L.append("")
    if ad.get("skip"):
        L.append("**Skip:** " + "; ".join(ad["skip"]))
        L.append("")

    L.append("---")
    L.append("_Generated by [oni](https://github.com/) — a clean-room reverse-engineering engine. "
             "oni extracts architecture and ideas; it never copies code. Verify the licence before adopting._")
    return "\n".join(L)
